#ifndef GUARD_CHAOS_RANCH_COSMETICS_H
#define GUARD_CHAOS_RANCH_COSMETICS_H
#define RANCH_TILE_RHYDON 735
#define RANCH_TILE_LAPRAS 739
#define RANCH_TILE_SNORLAX 743
#define RANCH_TILE_VENUSAUR 747
#define RANCH_TILE_CHARIZARD 751
#define RANCH_TILE_BLASTOISE 755
#define RANCH_TILE_BENCH 759
#define RANCH_TILE_FLOWERS 761
#define RANCH_TILE_FOUNTAIN 765
#define RANCH_TILE_FOREST 781
#define RANCH_TILE_BEACH 782
#define RANCH_TILE_SNOW 783
#define RANCH_TILE_NIGHT 784
#define RANCH_THEME_PROP_OFFSET 50
#define RANCH_THEME_PROP_STRIDE 46
#endif
