#include "global.h"
#include "constants/maps.h"
#include "constants/flags.h"
#include "constants/items.h"
#include <stddef.h>
const unsigned dungeonLayout[] = {
 MAP_GROUP(MAP_MT_MOON_1F), MAP_NUM(MAP_MT_MOON_1F),
 MAP_GROUP(MAP_MT_MOON_B1F), MAP_NUM(MAP_MT_MOON_B1F),
 MAP_GROUP(MAP_ROUTE4), MAP_NUM(MAP_ROUTE4),
 MAP_GROUP(MAP_ROCK_TUNNEL_1F), MAP_NUM(MAP_ROCK_TUNNEL_1F),
 MAP_GROUP(MAP_ROCK_TUNNEL_B1F), MAP_NUM(MAP_ROCK_TUNNEL_B1F),
 MAP_GROUP(MAP_ROUTE10), MAP_NUM(MAP_ROUTE10),
 MAP_GROUP(MAP_POKEMON_TOWER_1F), MAP_NUM(MAP_POKEMON_TOWER_1F),
 MAP_GROUP(MAP_POKEMON_TOWER_7F), MAP_NUM(MAP_POKEMON_TOWER_7F),
 MAP_GROUP(MAP_LAVENDER_TOWN), MAP_NUM(MAP_LAVENDER_TOWN),
 MAP_GROUP(MAP_ROCKET_HIDEOUT_B1F), MAP_NUM(MAP_ROCKET_HIDEOUT_B1F),
 MAP_GROUP(MAP_ROCKET_HIDEOUT_B4F), MAP_NUM(MAP_ROCKET_HIDEOUT_B4F),
 MAP_GROUP(MAP_CELADON_CITY_GAME_CORNER), MAP_NUM(MAP_CELADON_CITY_GAME_CORNER),
 MAP_GROUP(MAP_SILPH_CO_1F), MAP_NUM(MAP_SILPH_CO_1F),
 MAP_GROUP(MAP_SILPH_CO_11F), MAP_NUM(MAP_SILPH_CO_11F),
 MAP_GROUP(MAP_SAFFRON_CITY), MAP_NUM(MAP_SAFFRON_CITY),
 MAP_GROUP(MAP_POKEMON_MANSION_1F), MAP_NUM(MAP_POKEMON_MANSION_1F),
 MAP_GROUP(MAP_POKEMON_MANSION_B1F), MAP_NUM(MAP_POKEMON_MANSION_B1F),
 MAP_GROUP(MAP_CINNABAR_ISLAND), MAP_NUM(MAP_CINNABAR_ISLAND),
 MAP_GROUP(MAP_VICTORY_ROAD_1F_FRLG), MAP_NUM(MAP_VICTORY_ROAD_1F_FRLG),
 MAP_GROUP(MAP_VICTORY_ROAD_2F), MAP_NUM(MAP_VICTORY_ROAD_2F),
 MAP_GROUP(MAP_ROUTE23), MAP_NUM(MAP_ROUTE23),
 FLAG_RESCUED_MR_FUJI, FLAG_HIDE_HIDEOUT_GIOVANNI, FLAG_HIDE_SILPH_ROCKETS,
 ITEM_SILPH_SCOPE, ITEM_SECRET_KEY, ITEM_HM_STRENGTH, FLAG_BADGE08_GET,
 offsetof(struct SaveBlock1,location), offsetof(struct SaveBlock1,pos), ITEM_TM01,
};
