#include "global.h"
#include "constants/maps.h"
#include "constants/trainers.h"
#include "constants/flags.h"
#include "constants/map_types.h"
const unsigned worldLayout[8][14] = {
    {MAPSEC_PEWTER_CITY, MAP_GROUP(MAP_PEWTER_CITY_GYM), MAP_NUM(MAP_PEWTER_CITY_GYM), TRAINER_LEADER_BROCK, FLAG_DEFEATED_BROCK, 1, TRAINER_CAMPER_LIAM, 0, 0, 0, 0, 0, 0, 0},
    {MAPSEC_CERULEAN_CITY, MAP_GROUP(MAP_CERULEAN_CITY_GYM), MAP_NUM(MAP_CERULEAN_CITY_GYM), TRAINER_LEADER_MISTY, FLAG_DEFEATED_MISTY, 2, TRAINER_PICNICKER_DIANA, TRAINER_SWIMMER_MALE_LUIS, 0, 0, 0, 0, 0, 0},
    {MAPSEC_VERMILION_CITY, MAP_GROUP(MAP_VERMILION_CITY_GYM), MAP_NUM(MAP_VERMILION_CITY_GYM), TRAINER_LEADER_LT_SURGE, FLAG_DEFEATED_LT_SURGE, 3, TRAINER_SAILOR_DWAYNE, TRAINER_ENGINEER_BAILY, TRAINER_GENTLEMAN_TUCKER, 0, 0, 0, 0, 0},
    {MAPSEC_CELADON_CITY, MAP_GROUP(MAP_CELADON_CITY_GYM), MAP_NUM(MAP_CELADON_CITY_GYM), TRAINER_LEADER_ERIKA, FLAG_DEFEATED_ERIKA, 7, TRAINER_LASS_KAY, TRAINER_LASS_LISA, TRAINER_PICNICKER_TINA, TRAINER_BEAUTY_BRIDGET, TRAINER_BEAUTY_TAMIA, TRAINER_BEAUTY_LORI, TRAINER_COOLTRAINER_MARY, 0},
    {MAPSEC_FUCHSIA_CITY, MAP_GROUP(MAP_FUCHSIA_CITY_GYM), MAP_NUM(MAP_FUCHSIA_CITY_GYM), TRAINER_LEADER_KOGA, FLAG_DEFEATED_KOGA, 6, TRAINER_TAMER_PHIL, TRAINER_TAMER_EDGAR, TRAINER_JUGGLER_KIRK, TRAINER_JUGGLER_SHAWN, TRAINER_JUGGLER_KAYDEN, TRAINER_JUGGLER_NATE, 0, 0},
    {MAPSEC_SAFFRON_CITY, MAP_GROUP(MAP_SAFFRON_CITY_GYM), MAP_NUM(MAP_SAFFRON_CITY_GYM), TRAINER_LEADER_SABRINA, FLAG_DEFEATED_SABRINA, 7, TRAINER_PSYCHIC_JOHAN, TRAINER_PSYCHIC_TYRON, TRAINER_PSYCHIC_CAMERON, TRAINER_PSYCHIC_PRESTON, TRAINER_CHANNELER_AMANDA, TRAINER_CHANNELER_STACY, TRAINER_CHANNELER_TASHA, 0},
    {MAPSEC_CINNABAR_ISLAND, MAP_GROUP(MAP_CINNABAR_ISLAND_GYM), MAP_NUM(MAP_CINNABAR_ISLAND_GYM), TRAINER_LEADER_BLAINE, FLAG_DEFEATED_BLAINE, 7, TRAINER_SUPER_NERD_ERIK, TRAINER_SUPER_NERD_AVERY, TRAINER_SUPER_NERD_DEREK, TRAINER_SUPER_NERD_ZAC, TRAINER_BURGLAR_QUINN, TRAINER_BURGLAR_RAMON, TRAINER_BURGLAR_DUSTY, 0},
    {MAPSEC_VIRIDIAN_CITY, MAP_GROUP(MAP_VIRIDIAN_CITY_GYM), MAP_NUM(MAP_VIRIDIAN_CITY_GYM), TRAINER_LEADER_GIOVANNI, FLAG_DEFEATED_LEADER_GIOVANNI, 8, TRAINER_TAMER_JASON, TRAINER_TAMER_COLE, TRAINER_BLACK_BELT_ATSUSHI, TRAINER_BLACK_BELT_KIYO, TRAINER_BLACK_BELT_TAKASHI, TRAINER_COOLTRAINER_SAMUEL, TRAINER_COOLTRAINER_YUJI, TRAINER_COOLTRAINER_WARREN},
};
