Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"

gText_RunFilterReturnToCenter::
	.string "Your party breaks the active run rules.\pPlease fix your party inside the\nPOKéMON CENTER.$"

