gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"

gText_PlayerUsedSurf::
	.string "{PLAYER} used SURF!$"

Text_CurrentTooFast::
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"

Text_SurfToolMissing::
	.string "You'll need the SURF field tool\n"
	.string "to cross the water!$"

Text_SurfBadgeMissing::
	.string "A new GYM BADGE will let you\n"
	.string "use SURF outside of battle!$"
